### ISSUE TITLE
Ability to manually name layers

### ISSUE THREAD

**Issue by avdstaaij** [sjmikler/pytorch-symbolic#29]
First of all, thank you for writing this library! It has been quite useful to me so far.

It would be useful if you could manually name the layers of a `SymbolicModel`, perhaps via the interception of a specific keyword argument in the module call wrapper. For example (mockup):
```python3
>>> import torch.nn as nn
>>> from pytorch_symbolic import Input, SymbolicModel
>>>
>>> x = Input((1,1))
>>> y = nn.Conv2d(1,1,1)(x, name="MyCustomName")
>>> model = SymbolicModel(x, y)
>>>
>>> model.summary()
>>> print(model.state_dict().keys())
```
```
_________________________________________________
     Layer      Output shape   Params   Parent   
=================================================
1    Input_1      (None, 1, 1)   0                 
2*   MyCustomName (None, 1, 1)   2        1        
=================================================
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________
odict_keys(['MyCustomName.weight', 'MyCustomName.bias'])
```

This would particularly help to improve clarity when using nested SymbolicModels.

**Comment by sjmikler** [comment]
Will do.

**Comment by sjmikler** [comment]
This has been added in the latest 1.0.6 version.

Your code (modified):
```
import torch.nn as nn

from pytorch_symbolic import Input, SymbolicModel

x = Input((1, 1))
y = nn.Conv2d(1, 1, 1)(x, custom_name="MyCustomName")
z = nn.Conv2d(1, 1, 1)(x, custom_name="MyCustomName")
model = SymbolicModel(x, y + z)

model.summary()
print(model.state_dict().keys())
```

Produces:
```
_______________________________________________________
     Layer            Output shape   Params   Parent   
=======================================================
1    Input_1          (None, 1, 1)   0                 
2    MyCustomName_1   (None, 1, 1)   2        1        
3    MyCustomName_2   (None, 1, 1)   2        1        
4*   AddOpLayer_1     (None, 1, 1)   0        2,3      
=======================================================
Total params: 4
Trainable params: 4
Non-trainable params: 0
_______________________________________________________
odict_keys(['MyCustomName_1.weight', 'MyCustomName_1.bias', 'MyCustomName_2.weight', 'MyCustomName_2.bias'])
```

This new kwarg `custom_name` should work for all three ways of adding a layer to the model:
* outputs = inputs(layer, custom_name="YOUR_CUSTOM_NAME")
* outputs = layer(inputs, custom_name="YOUR_CUSTOM_NAME")
* outputs = add_to_graph(layer, inputs, custom_name="YOUR_CUSTOM_NAME")

Thanks for opening the issue. I am closing it, but let me know if there's anything else.

**Comment by avdstaaij** [comment]
Apologies for the late response. Works perfectly!

For the purposes of re-using trained weights in a slightly different architecture, it would have been nice to have a way of suppressing the automatic indexing ("_1", "_2") as well (with perhaps an exception on a duplicate name), but this is a very minor point.

**Comment by avdstaaij** [comment]
Even better!
I think suppressing the indexing for the first occurrence is already a pretty good compromise.
